### ISSUE TITLE
Iterator bug

### ISSUE THREAD

**Issue by Scroph** [domnikl/DesignPatternsPHP#232]
The following code doesn't produce the expected output :

	<?php
	require_once 'Book.php';
	require_once 'BookList.php';
	require_once 'BookListIterator.php';

	use DesignPatterns\Behavioral\Iterator\Book;
	use DesignPatterns\Behavioral\Iterator\BookList;
	use DesignPatterns\Behavioral\Iterator\BookListIterator;

	$list = new BookList();
	$list->addBook(new Book('foo', 'bar'));
	$list->addBook(new Book('a', '1'));
	$list->addBook(new Book('b', '2'));
	$list->addBook(new Book('c', '3'));
	$list->addBook(new Book('d', '4'));

	$list->removeBook(new Book('b', '2'));

	$it = new BookListIterator($list);
	foreach($it as $i => $b)
		echo $b->getAuthorAndTitle(), PHP_EOL;

The output is :

	foo by bar
	a by 1

When it should be :

	foo by bar
	a by 1
	c by 3
	d by 4

The reason why this happens is that after deleting the "b by 2" book, the internal array of BookList looks like this :

	Array
	(
	    [0] => DesignPatterns\Behavioral\Iterator\Book Object
		(
		    [author:DesignPatterns\Behavioral\Iterator\Book:private] => bar
		    [title:DesignPatterns\Behavioral\Iterator\Book:private] => foo
		)

	    [1] => DesignPatterns\Behavioral\Iterator\Book Object
		(
		    [author:DesignPatterns\Behavioral\Iterator\Book:private] => 1
		    [title:DesignPatterns\Behavioral\Iterator\Book:private] => a
		)

	    [3] => DesignPatterns\Behavioral\Iterator\Book Object
		(
		    [author:DesignPatterns\Behavioral\Iterator\Book:private] => 3
		    [title:DesignPatterns\Behavioral\Iterator\Book:private] => c
		)

	    [4] => DesignPatterns\Behavioral\Iterator\Book Object
		(
		    [author:DesignPatterns\Behavioral\Iterator\Book:private] => 4
		    [title:DesignPatterns\Behavioral\Iterator\Book:private] => d
		)

	)

You'll notice that the index 2 is missing, which makes sense since removeBook calls unset() on that specific book. However, BookListIterator's next() method simply increments the internal index ($currentBook) and BookListIterator::valid() stops when BookList::getBook() returns `null`, which happens once BookListIterator::currentBook reaches 2, the book we just removed by calling $list->removeBook(new Book('b', '2')). Because of this, the iterator stops prematurely.

**Comment by axelitus** [comment]
Indeed it does not work for the reasons you state. In my opinion this code serves the purpose of merely giving you an example of how this would be implemented and thus lacks many things you would do in production. This examples are just a starting point, not a solution for every problem nor a complete implementation of production-ready code.

Having said that, in my opinion there's nothing wrong with the given code but it's true it is very limited and can be improved in so many ways, but that would depend on the particularities of what your program needs. To _fix_ your specific case one could do one of two things:
1. Re-index the book list whenever a book is removed
2. Refactoring the iterator behavior to make it resilient to indexing inconsistencies.

It would all depend on what you want to achieve with your code, sometimes the first option would be best, sometimes the latter.

As a conclusion, modifying a collection that needs to/is being iterated over, always presents its challenges and is not an easy topic when one needs to address consistency around iterations (this is specially problematic when the collection is modified while being iterated as the iterator may reach an unstable status due to changes).

**Comment by Scroph** [comment]
Maybe the bug I pointed out is beyond the scope of this tutorial. The solution I intended to suggest in the OP makes use of the IteratorIterator class. My plan was to make BookList extend IteratorIterator so that it inherits the methods that will make it compatible with foreach loops. I would then pass it the $bookList array in BookLists' constructor and make BookList implement Iterator. But then I thought about it and I realized that this approach will provide no educational value on how to make the iterator pattern, it would only teach how to use it.

>this is specially problematic when the collection is modified while being iterated as the iterator may reach an unstable status due to changes

I couldn't agree more, I can only imagine what a headache that would be.

By the way, I don't know UML but diagram seems to imply that the reverse iterator inherits from the normal one. The BookListReverseIterator class, however, doesn't extend BookListIterator.

**Comment by axelitus** [comment]
I think you may have pinpointed the main struggle here: the purpose of this repo, as I understand, is to be educational. And in that sense the examples and code given clearly teach the patterns and give a basic example of how one can use them. For that matter leaving the code as simple as possible containing only the code needed for the pattern to be implemented is important.

There's a related discussion going on about examples [here](https://github.com/domnikl/DesignPatternsPHP/issues/175). For me this question sums it all up: _How much is barely enough and to what extent it's all about too much?_. I think the code should have sufficient implementation details to demonstrate the pattern, but not too much to divert from the real purpose.

Let's remember that _educational_ does not necessarily mean _perfect_ or even _complete_ for that matter and thus not every problem is solved in the given examples.

**Comment by domnikl** [comment]
While I agree with @axelitus in that this is just an educational resource to learn the patterns I too would love to have only bug-free examples in it. I just started working on a solution and the code needs some cleanup and more documentation, too. Also I no longer think the getBook() method in BookList is a good idea (using internal IDs to get books from outside?) + the reverse iterator makes no sense and is just too much in there.

@Scroph IteratorIterator might seem legible, but to keep things simple, I think BookList should just implement Iterator and thats it. ReverseIterator is just too much, as it just doubles the amount of code just to count down instead of up.

**Comment by domnikl** [comment]
Got a PR for it. What do you think about it @Scroph?

**Comment by axelitus** [comment]
At fist glance it seems this works, though in my opinion it's overkill to call array_keys on each Iterator function. I know the point is not to show the most polished code ever created and adding more code would probably take focus away from the main subject, so I'm ok with this new re-factoring and hopefully it will be understood that this is not the most efficient way to do it.

**Comment by Scroph** [comment]
That's an clever way to solve it ! I see you also added some PHP7 features, which is pretty good. But what do you think about @axelitus's method of reindexing the array after the removal ? Something like this for example :

    public function removeBook(Book $bookToRemove)
    {
        foreach ($this->books as $key => $book) {
            /** @var Book $book */
            if ($book->getAuthorAndTitle() === $bookToRemove->getAuthorAndTitle()) {
                unset($this->books[$key]);
            }
        }
        $this->books = array_values($this->books);
    }

This has the benefit of not having to call array_keys in the methods that BookList implements from Iterator, and also makes the code easier to grasp. As far as bugs are concerned, I can't think of anything wrong with either approach so whichever one you choose is fine.

If I may suggest just one more modification : maybe add a constructor where the $books property is initialized to an empty array. I say this because accidentally trying to remove a book or looping through a newly instantiated BookList class will cause the interpreter to complain, respectively, about the argument of foreach not being valid and array_keys' argument not being an array. But I'm just nitpicking, it's unlikely that this will happen even the code were to be used in production.

**Comment by domnikl** [comment]
You are right, I fixed it and used the solution from @axelitus with `array_values()` and initialised the $this->books instead of adding a constructor. Tests are working, is this what you meant?

**Comment by axelitus** [comment]
I think this is easy to understand and correct enough for a basic example.

**Comment by domnikl** [comment]
Perfect thanks for your feedback, I merged it!
