### ISSUE TITLE
Confusion between AbstractFactory and FactoryMethod

### ISSUE THREAD

**Issue by Cevantime** [domnikl/DesignPatternsPHP#328]
I might be mistaken but it seems to me that there is an inversion between the AbstractFactory pattern and the FactoryMethod pattern.
Anyway, thank you for this awesome work.

**Comment by domnikl** [comment]
Hi @Cevantime, a lot of people seem to confuse these two patterns and sometimes use their names interchangeably. But there is a difference between them: 
Factory method is about a single method defined in an interface or abstract class that subclasses need to implement in order to create similar objects whereas Abstract Factory is a whole object that creates other related or dependent objects.

Factory Method pattern:
It's purpose is to define a contract as a method (LoggerFactory) on how to create a type of object (Logger) and let subclasses decide which concrete type is being created (StdoutLoggerFactory creates a StdoutLogger and FileLoggerFactory creates FileLogger objects).

Abstract Factory pattern:
It's all about creating dependent or similar types of objects (Parser). I skipped creating an interface for ParserFactory in this example to keep it simple and small and it is not always necessary. I often use this pattern to create a factory that is capable of creating all sorts of objects my application needs to run like instances of PDO or mysqli, Twig and so on.

**Comment by Cevantime** [comment]
Thank you for your quick reply. It seems that I am mistaken, after all !  I had a wrong idea of the nature of both pattern. Sorry, I guess you can close this issue.
